# Generated by Django 3.1.1 on 2020-09-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamecategory_player_playerscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('name',)},
        ),
    ]
